language: go
go:
  - 1.x
os:
  - osx

before_install:
  - brew update
  - brew install node
  - go get github.com/FactomProject/staticfiles
  - curl https://glide.sh/get | sh
  - brew cask install java
install:
  - cd $GOPATH/src/github.com/FactomProject/enterprise-wallet
  - bash make.sh
  - cd electron-wrapper/app
  - npm install
  - cd ..
  - npm install
  - npm run dist:mac
script:
  - ls $GOPATH/src/github.com/FactomProject/enterprise-wallet/electron-wrapper/dist