language: go
go:
        - 1.7.4
before_install:
        - go get github.com/mattn/goveralls
install:
        - go get -v github.com/Masterminds/glide
        - cd $GOPATH/src/github.com/Masterminds/glide && git checkout tags/v0.12.3 && go install && cd -
        - glide install
script:
        - go build -v