language: go
go:
        - 1.7.4
before_install:
        - go get github.com/mattn/goveralls
        - go get github.com/FactomProject/factomd
install:
        - go get -v github.com/Masterminds/glide
        - cd $GOPATH/src/github.com/Masterminds/glide && git checkout tags/v0.12.3 && go install && cd -
        - glide install
script:
        - go build -v
        - cd $GOPATH/src/github.com/FactomProject/factomd && git checkout develop && glide install
        - go build -v
        - nohup ./factomd -network=LOCAL -db=Map -blktime=1 &
        - cd $GOPATH/src/github.com/FactomProject/enterprise-wallet
        - go test -v $(glide nv)
        - killall factomd
        - "$GOPATH/bin/goveralls -service=travis-ci"