var $jscomp={scope:{},checkStringArgs:function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""}};
$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,b,c,g){if(b){c=$jscomp.global;a=a.split(".");for(g=0;g<a.length-1;g++){var q=a[g];q in c||(c[q]={});c=c[q]}a=a[a.length-1];g=c[a];b=b(g);b!=g&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};
$jscomp.polyfill("String.prototype.startsWith",function(a){return a?a:function(a,c){var b=$jscomp.checkStringArgs(this,a,"startsWith");a+="";for(var q=b.length,h=a.length,v=Math.max(0,Math.min(c|0,b.length)),u=0;u<h&&v<q;)if(b[v++]!=a[u++])return!1;return u>=h}},"es6-impl","es3");$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var g=a.length,q=0;q<g;q++){var h=a[q];if(b.call(c,h,q,a))return{i:q,v:h}}return{i:-1,v:void 0}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6-impl","es3");$jscomp.polyfill("String.prototype.includes",function(a){return a?a:function(a,c){return-1!==$jscomp.checkStringArgs(this,a,"includes").indexOf(a,c||0)}},"es6-impl","es3");
function LoadInitialAddresses(){resp=getRequest("addresses-no-bal",function(a){obj=JSON.parse(a);null!=obj.FactoidAddresses.List&&obj.FactoidAddresses.List.forEach(function(a){$("#factoid-addresses-table tbody").append(addressTableRow(a,"factoid",!0))});null!=obj.EntryCreditAddresses.List&&obj.EntryCreditAddresses.List.forEach(function(a){$("#credit-addresses-table tbody").append(addressTableRow(a,"entry-credits",!0))});null!=obj.ExternalAddresses.List&&obj.ExternalAddresses.List.forEach(function(a){$("#external-addresses-table tbody").append(addressTableRow(a,
"external",!0))});sortNames(!0)})}
function LoadAddresses(){LoadInitialAddresses();resp=getRequest("addresses",function(a){obj=JSON.parse(a);null!=obj.FactoidAddresses.List&&($("#factoid-addresses-table tbody").html(""),obj.FactoidAddresses.List.forEach(function(a){$("#factoid-addresses-table tbody").append(addressTableRow(a,"factoid",!1))}));null!=obj.EntryCreditAddresses.List&&($("#credit-addresses-table tbody").html(""),obj.EntryCreditAddresses.List.forEach(function(a){$("#credit-addresses-table tbody").append(addressTableRow(a,"entry-credits",
!1))}));null!=obj.ExternalAddresses.List&&($("#external-addresses-table tbody").html(""),obj.ExternalAddresses.List.forEach(function(a){$("#external-addresses-table tbody").append(addressTableRow(a,"external",!1))}));sortNames(!0)})}
function addressTableRow(a,b,c){a.Address.startsWith("FA")?(token=" FCT",a.Balance=Number(a.Balance.toFixed(4))):token=" EC";c&&(a.Balance="...",token="");star='<small><span id="star" class="fa fa-star-o" aria-hidden="true" value="0"></span></small>';a.Seeded&&(star='<small><span id="star" class="fa fa-star" aria-hidden="true" value="1"></span></small>');"external"==b&&(star="");shortAddr=a.Address;return'<tr><td><a nav-click="true" href="receive-factoids?address='+a.Address+"&name="+a.Name+'"><i class="qr"><img src="img/icon_qr.svg" class="svg"></i></a></td><td><span id="name">'+
a.Name+'</span> <a nav-click="true" href="edit-address-'+b+"?address="+a.Address+"&name="+a.Name+'"><i class="edit"><img src="img/icon_edit.svg" class="svg"></i></a></td><td><pre>'+star+" "+shortAddr+'</pre></td><td><span id="balance">'+a.Balance+"</span>"+token+"</td></tr>"}function ResetNotMe(a){0!=a&&resetNameSort();1!=a&&resetBalancesSort();2!=a&&resetSeededSort()}
$("table").on("click","#sort-names",function(a){ResetNotMe(0);$("#sort-names-icon").hasClass("fa-sort")?($("th #sort-names-icon").removeClass("fa-sort"),$("th #sort-names-icon").addClass("fa-sort-desc"),sortNames(!0)):$("#sort-names-icon").hasClass("fa-sort-asc")?($("th #sort-names-icon").removeClass("fa-sort-asc"),$("th #sort-names-icon").addClass("fa-sort-desc"),sortNames(!0)):$("#sort-names-icon").hasClass("fa-sort-desc")&&($("th #sort-names-icon").removeClass("fa-sort-desc"),$("th #sort-names-icon").addClass("fa-sort-asc"),
sortNames(!1))});function resetNameSort(){$("th #sort-names-icon").removeClass("fa-sort-asc");$("th #sort-names-icon").removeClass("fa-sort-desc");$("th #sort-names-icon").addClass("fa-sort")}
function sortNames(a){array=$("#factoid-addresses-table tbody tr").get();valArray=$("#factoid-addresses-table tbody tr").find("#name").get();array=generalSort(stringLessThan,array,valArray,a,a);$("#factoid-addresses-table tbody").html(array);array=$("#credit-addresses-table tbody tr").get();valArray=$("#credit-addresses-table tbody tr").find("#name").get();array=generalSort(stringLessThan,array,valArray,a,a);$("#credit-addresses-table tbody").html(array);array=$("#external-addresses-table tbody tr").get();
valArray=$("#external-addresses-table tbody tr").find("#name").get();array=generalSort(stringLessThan,array,valArray,a,a);$("#external-addresses-table tbody").html(array)}
$("table").on("click","#sort-balances",function(a){ResetNotMe(1);$("#sort-balances-icon").hasClass("fa-sort-amount")?($("th #sort-balances-icon").removeClass("fa-sort-amount"),$("th #sort-balances-icon").addClass("fa-sort-amount-desc"),sortBalances(!1)):$("#sort-balances-icon").hasClass("fa-sort-amount-asc")?($("th #sort-balances-icon").removeClass("fa-sort-amount-asc"),$("th #sort-balances-icon").addClass("fa-sort-amount-desc"),sortBalances(!1)):$("#sort-balances-icon").hasClass("fa-sort-amount-desc")&&
($("th #sort-balances-icon").removeClass("fa-sort-amount-desc"),$("th #sort-balances-icon").addClass("fa-sort-amount-asc"),sortBalances(!0))});function resetBalancesSort(){$("th #sort-balances-icon").removeClass("fa-sort-amount-asc");$("th #sort-balances-icon").removeClass("fa-sort-amount-desc");$("th #sort-balances-icon").addClass("fa-sort-amount")}
function sortBalances(a){array=$("#factoid-addresses-table tbody tr").get();valArray=$("#factoid-addresses-table tbody tr").find("#balance").get();array=generalSort(isLessThan,array,valArray,a,a);$("#factoid-addresses-table tbody").html(array);array=$("#credit-addresses-table tbody tr").get();valArray=$("#credit-addresses-table tbody tr").find("#balance").get();array=generalSort(isLessThan,array,valArray,a,a);$("#credit-addresses-table tbody").html(array);array=$("#external-addresses-table tbody tr").get();
valArray=$("#external-addresses-table tbody tr").find("#balance").get();array=generalSort(isLessThan,array,valArray,a,a);$("#external-addresses-table tbody").html(array)}
$("table").on("click","#sort-seeded",function(a){ResetNotMe(2);$("#sort-seeded-icon").hasClass("fa-sort")?($("th #sort-seeded-icon").removeClass("fa-sort"),$("th #sort-seeded-icon").addClass("fa-sort-desc"),sortSeeded(!1)):$("#sort-seeded-icon").hasClass("fa-sort-asc")?($("th #sort-seeded-icon").removeClass("fa-sort-asc"),$("th #sort-seeded-icon").addClass("fa-sort-desc"),sortSeeded(!1)):$("#sort-seeded-icon").hasClass("fa-sort-desc")&&($("th #sort-seeded-icon").removeClass("fa-sort-desc"),$("th #sort-seeded-icon").addClass("fa-sort-asc"),
sortSeeded(!0))});function resetSeededSort(){$("th #sort-seeded-icon").removeClass("fa-sort-asc");$("th #sort-seeded-icon").removeClass("fa-sort-desc");$("th #sort-seeded-icon").addClass("fa-sort")}
function sortSeeded(a){array=$("#factoid-addresses-table tbody tr").get();valArray=$("#factoid-addresses-table tbody tr").get();array=generalSort(starLessThan,array,valArray,a,!0);$("#factoid-addresses-table tbody").html(array);array=$("#credit-addresses-table tbody tr").get();valArray=$("#credit-addresses-table tbody tr").get();array=generalSort(starLessThan,array,valArray,a,!0);$("#credit-addresses-table tbody").html(array)}
function generalSort(a,b,c,g,q){peerLen=c.length;for(index=0;index<peerLen;index++){tmpVal=c[index];tmp=b[index];if(1==g||q)for(j=index-1;-1<j&&!a(c[j],tmpVal,g);j--)c[j+1]=c[j],b[j+1]=b[j];else for(j=index-1;-1<j&&a(c[j],tmpVal,g);j--)c[j+1]=c[j],b[j+1]=b[j];c[j+1]=tmpVal;b[j+1]=tmp}return b}
function starLessThan(a,b,c){as=$(a).find("#star");bs=$(b).find("#star");aN=$(as).attr("value");bN=$(bs).attr("value");c||(aN=flipInt(aN),bN=flipInt(bN));aM=aN+$(a).find("#name").text();bM=bN+$(b).find("#name").text();return String(aM)<String(bM)?1:0}function flipInt(a){return 1==Number(a)?0:1}function stringLessThan(a,b,c){return String(a.innerText)<String(b.innerText)?1:0}function isLessThan(a,b,c){return Number(a.innerText)<Number(b.innerText)?1:0}ContentLen=CurrentCount=0;LoopstopIncrement=15;
Loopstop=20;var Transactions=[];Done=!1;
function LoadTransactions(){getRequest("related-transactions",function(a){obj=JSON.parse(a);if("none"==obj.Error&&null==obj.Content)setTimeout(function(){LoadTransactions()},5E3);else if($("#loading-container").remove(),"none"!=obj.Error)SetGeneralError(obj.Error);else if(ContentLen=obj.Content.length,Transactions=obj.Content,0<obj.Content.length&&"empty"==obj.Content[0].TxID)SetGeneralError("Your addresses do not have any transactions in the blockchain. It could be the blockchain is not fully synced, the Control Panel will inform you of your current height. Please try again in a few minutes.");else if(0!=
obj.Content.length)for(ContentLen<Loopstop&&(Loopstop=ContentLen);CurrentCount<Loopstop;CurrentCount++)AppendNewTransaction(Transactions[CurrentCount],CurrentCount)})}Empty=!1;
function LoadCached(){if(!Empty)for(ContentLen<2*Loopstop&&(j=JSON.stringify({Current:ContentLen,More:5*Loopstop}),postRequest("more-cached-transaction",j,function(a){obj=JSON.parse(a);"none"==obj.Error&&null!=obj.Content&&(0==obj.Content.length?Empty=!0:(ContentLen+=obj.Content.length,Transactions=Transactions.concat(obj.Content)))})),ContentLen<Loopstop&&(Loopstop=ContentLen);CurrentCount<Loopstop;CurrentCount++)AppendNewTransaction(Transactions[CurrentCount],CurrentCount)}
function AppendNewTransaction(a,b){if(1==a.Action[0]){pic="sent";amt=0;token="FCT";addrs="";for(var c=0;c<a.Inputs.length;c++)""!=a.Inputs[c].Name&&(addrs+='<div class="nick">'+a.Inputs[c].Name+'<pre class="show-for-large"> ('+a.Inputs[c].Address+")</pre></div>",amt+=a.Inputs[c].Amount/1E8);appendTrans(pic,b,-1*amt,token,a.Date,addrs)}if(1==a.Action[1]){pic="received";amt=0;token="FCT";addrs="";for(c=0;c<a.Outputs.length;c++)""!=a.Outputs[c].Name&&a.Outputs[c].Address.startsWith("FA")&&(addrs+='<div class="nick">'+
a.Outputs[c].Name+'<pre class="show-for-large percent95"> ('+a.Outputs[c].Address+")</pre></div>",amt+=a.Outputs[c].Amount/1E8);appendTrans(pic,b,amt,token,a.Date,addrs)}if(1==a.Action[2]){pic="converted";amt=0;token="FCT";addrs="";for(c=0;c<a.Outputs.length;c++)""!=a.Outputs[c].Name&&a.Outputs[c].Address.startsWith("EC")&&(addrs+='<div class="nick">'+a.Outputs[c].Name+'<pre class="show-for-large percent95"> ('+a.Outputs[c].Address+")</pre></div>",amt+=a.Outputs[c].Amount/1E8);appendTrans(pic,b,amt,
token,a.Date,addrs)}}function appendTrans(a,b,c,g,q,h){$("#transaction-list").append('<tr><td><a id="transaction-link" data-toggle="transDetails" value="'+b+'"><i class="transIcon '+a+'"><img src="img/transaction_'+a+'.svg" class="svg"></i></a></td><td>'+q+' : <a value="'+b+'" id="transaction-link" data-toggle="transDetails">'+a.capitalize()+"</a>"+h+'</td><td style="word-wrap: break-word;">'+Number(c.toFixed(4))+" "+g+"</td></tr>")}
$("main").bind("scroll",function(){$("main").scrollTop()+$("main").innerHeight()>=.8*$("main").prop("scrollHeight")&&(Loopstop+=LoopstopIncrement,LoadCached())});LOCAL_EXPLORER=!0;
$("#transaction-list").on("click","#transaction-link",function(){port=$("#controlpanel-port").text();setTransDetails($(this).attr("value"));$("#transDetails #link").attr("href","http://explorer.factom.org/tx/"+Transactions[$(this).attr("value")].TxID);-1==port?(LOCAL_EXPLORER=!1,$("#transDetails #local-link").addClass("disabled-input"),$("#transDetails #local-link").prop("disabled",!0),$("#transDetails #local-link").attr("href","")):$("#transDetails #local-link").attr("href","http://localhost:"+port+
"/search?input="+Transactions[$(this).attr("value")].TxID+"&type=facttransaction")});$("#transDetails #local-link").click(function(a){LOCAL_EXPLORER||a.preventDefault()});
function setTransDetails(a){trans=Transactions[a];$("#trans-detail-txid").text(trans.TxID);$("#trans-details-inputs").html("");for(a=0;a<trans.Inputs.length;a++)$("#trans-details-inputs").append("<tr><td>"+trans.Inputs[a].Address+"</td><td>"+FCTNormalize(trans.Inputs[a].Amount)+" FCT</td></tr>");$("#trans-details-outputs").html("");for(a=0;a<trans.Outputs.length;a++)$("#trans-details-outputs").append("<tr><td>"+trans.Outputs[a].Address+"</td><td>"+FCTNormalize(trans.Outputs[a].Amount)+" FCT</td></tr>");
$("#trans-details-outputs").append('<tr class="total"><td> Total </td><td>'+FCTNormalize(trans.TotalInput)+" FCT</td></tr>");$("#total-transacted").text(FCTNormalize(trans.TotalECOutput+trans.TotalFCTOutput));$("#trans-date").text(trans.Date+" at "+trans.Time)}String.prototype.capitalize=function(){return this.charAt(0).toUpperCase()+this.slice(1)};importexport=!1;PageTokenABR="FCT";PageToken="factoids";AddressPrefix="FA";PageTransType="factoid";
"1"==$("#token-header").attr("value")?(PageTokenABR="EC",PageToken="entry credits",AddressPrefix="EC",PageTransType="ec"):"2"==$("#token-header").attr("value")&&(importexport=!0);counter=2;
function addNewOutputAddress(a,b,c,g){eClass="";c&&(eClass="input-group-error");str="factoid";"FCT"!=PageTokenABR&&(str="entry credit");defAdd='<pre><input id="output-factoid-address" type="text" name="output1" class="input-group-field percent95" placeholder="Type '+str+' address"></pre>';""!=a&&(defAdd='<pre><input id="output-factoid-address" type="text" name="output1" class="input-group-field percent95" placeholder="Type '+str+' address" value="'+a+'"></pre>');defAmt='<input id="output-factoid-amount" type="text" class="input-group-field" name="output1-num" placeholder="Amount of '+
PageToken+'">';0!=b&&(defAmt='<input id="output-factoid-amount" type="text" class="input-group-field" name="output1-num" placeholder="Amount of '+PageToken+'" value="'+b+'">');button='<a id="remove-new-output" class="button expanded newMinus">&nbsp;</a>';g&&(button='<a id="append-new-output" class="button expanded newPlus">&nbsp;</a>');$("#all-outputs").append('<div class="row single-output-'+counter+'" id="single-output">    <div class="small-12 medium-7 large-8 columns">        <div class="input-group '+
eClass+'" id="output-factoid-address-container">        '+defAdd+'        <a id="addressbook-button" data-toggle="addressbook" class="input-group-button button input-group-field" id="addressbook" value="'+counter+'"><i class="fa fa-book"></i></a>        </div>    </div>    <div class="small-10 medium-4 large-3 columns">        <div class="input-group">            '+defAmt+'            <span class="input-group-label">'+PageTokenABR+'</span>        </div>    </div>    <div class="small-2 medium-1 columns">            '+
button+"    </div></div>");counter+=1}$("#append-new-output").click(function(){$(this).hasClass("disabled-input")||addNewOutputAddress("",0,!0,!1)});
function addNewInputAddress(a,b,c,g){eClass="";c&&(eClass="input-group-error");defAmt='<input id="input-factoid-amount" type="text" class="input-group-field" name="output1-num" placeholder="Amount of factoids">';0!=b&&(defAmt='<input id="input-factoid-amount" type="text" class="input-group-field" name="output1-num" placeholder="Amount of factoids" value="'+b+'">');defAdd='<pre><input id="input-factoid-address" type="text" name="input1" class="input-group-field percent95 disabled-input" placeholder="Choose factoid address" disabled></pre>';
""!=a&&(defAdd='<pre><input id="input-factoid-address" type="text" name="input1" class="input-group-field percent95 disabled-input" placeholder="Choose factoid address" disabled value="'+a+'"></pre>');button='<a id="remove-new-input" class="button expanded newMinus">&nbsp;</a>';g&&(button='<a id="append-new-input" class="button expanded newPlus">&nbsp;</a>');$("#all-inputs").append('<div class="row single-input-'+counter+'" id="single-input">    <div class="small-12 medium-7 large-8 columns">        <div class="input-group '+
eClass+'" id="input-factoid-address-container">        '+defAdd+'        <a id="addressbook-button" data-toggle="fee-addressbook" class="input-group-button button input-group-field" id="addressbook" value="'+counter+'"><i class="fa fa-book"></i></a>        </div>    </div>    <div class="small-10 medium-4 large-3 columns">        <div class="input-group">            '+defAmt+'            <span class="input-group-label">FCT</span>        </div>    </div>    <div class="small-2 medium-1 columns">            '+
button+"    </div></div>");counter+=1}$("#append-new-input").click(function(){$(this).hasClass("disabled-input")||addNewInputAddress("",0,!0,!1)});$("#all-outputs").on("click","#remove-new-output",function(){jQuery(this).parent().parent().remove()});$("#all-inputs").on("click","#remove-new-input",function(){jQuery(this).parent().parent().remove()});
$("#all-outputs").on("keypress","#output-factoid-amount",function(a){if("FCT"==PageTokenABR){var b=$(this);b.val(b.val().replace(/[^0-9\.]/g,""));46==a.which&&b.val().indexOf(".");decSplit=$(this).val().split(".");2<decSplit.length&&a.preventDefault()}else b=$(this),b.val(b.val().replace(/[^0-9\.]/g,"")),(48>a.which||57<a.which)&&8!=a.which&&a.preventDefault()});$("#all-outputs").on("change","#output-factoid-amount",function(){});$("#all-outputs").on("click","#output-factoid-address-container",function(){$(this).removeClass("input-group-error")});
$("#all-inputs").on("click","#input-factoid-amount",function(){$(this).removeClass("input-group-error")});$("#all-outputs").on("click","#output-factoid-amount",function(){$(this).removeClass("input-group-error")});$("#make-entire-transaction").on("click",function(){Input&&("1"==$(this).attr("value")?$("#sign-transaction").prop("checked")?MakeTransaction(!0):MakeTransaction(!1):MakeTransaction(!0))});
function MakeTransaction(a){transObject=getTransactionObject(!0);null!=transObject&&void 0!=transObject&&(a||(transObject.TransType="nosig"),null!=transObject&&(j=JSON.stringify(transObject),postRequest("make-transaction",j,function(a){obj=JSON.parse(a);if("none"==obj.Error){disableInput();ShowNewButtons();totalInput=obj.Content.Total/1E8;feeFact=obj.Content.Fee/1E8;total=totalInput+feeFact;if(""!=transObject.FeeAddress)for(a=0;a<transObject.OutputAddresses.length;a++)if(transObject.OutputAddresses[a]==
transObject.FeeAddress){total=totalInput-feeFact;break}$("#transaction-total").attr("value",total);$("#transaction-fee").attr("value",feeFact);importexport?(setExportDownload(obj.Content.Json),SetGeneralSuccess('Click "Export Transaction" to download, or go back to editing it')):SetGeneralSuccess('Click "Send Transaction" to send, or go back to editing it')}else SetGeneralError("Error: "+obj.Error)})))}
function setExportDownload(a){obj=JSON.parse(a);console.log(obj.params.transaction);fileExt=Date.now();$("#export-transaction").click(function(){saveTextAsFile(obj.params.transaction,"Exported-"+fileExt)})}$("#send-entire-transaction").on("click",function(){SendTransaction()});
function getTransactionObject(a){var b={TransType:PageTransType,OutputAddresses:[],OutputAmounts:[],InputAddresses:[],InputAmounts:[],FeeAddress:""};errMessage="";feeErr=amtErr=faErr=!1;$("#all-outputs #single-output").each(function(){err=!1;add=$(this).find("#output-factoid-address").val();add.startsWith(AddressPrefix)||importexport||($(this).find("#output-factoid-address-container").addClass("input-group-error"),err=faErr=!0);amt=$(this).find("#output-factoid-amount").val();if(0==Number(amt)||void 0==
amt||""==amt)$(this).find("#output-factoid-amount").addClass("input-group-error"),err=amtErr=!0;b.OutputAddresses.push(add);b.OutputAmounts.push(amt)});a&&!$("#coin-control").hasClass("coin-control")&&($("#all-inputs #single-input").each(function(){add=$(this).find("#input-factoid-address").val();add.startsWith("FA")||($(this).find("#input-factoid-address-container").addClass("input-group-error"),err=faErr=!0);amt=$(this).find("#input-factoid-amount").val();if(0==Number(amt)||void 0==amt||""==amt)$(this).find("#input-factoid-amount").addClass("input-group-error"),
err=amtErr=!0;b.InputAddresses.push(add);b.InputAmounts.push(amt)}),b.FeeAddress=$("#fee-factoid-address").val(),52>b.FeeAddress.length&&($("#fee-factoid-address").addClass("input-group-error"),err=feeErr=!0),b.TransType="custom");return err?(faErr&&(errMessage+="Addresses must start with '"+AddressPrefix+"'. "),amtErr&&(errMessage+="Amounts should not be 0. "),feeErr&&(errMessage+="Fee Address must be given. "),SetGeneralError("Error(s): "+errMessage),null):b}
$("#needed-input-button").on("click",function(a){Input?GetNeededInput():a.preventDefault()});InputLeft=TotalNeeded=CurrentInput=0;
function GetNeededInput(){transObject=getTransactionObject(!0);if(null!=transObject){for(var a=CurrentInput=0;a<transObject.InputAmounts.length;a++)void 0!=transObject.InputAmounts[a]&&(CurrentInput+=Number(transObject.InputAmounts[a]));j=JSON.stringify(transObject);postRequest("get-needed-input",j,function(a){obj=JSON.parse(a);if("none"==obj.Error){if(null!=obj.Content||void 0!=obj.Content)$("#input-needed-amount").val(FCTNormalize(obj.Content)),console.log(CurrentInput),TotalNeeded=FCTNormalize(obj.Content),
InputLeft=TotalNeeded-CurrentInput;HideMessages()}else SetGeneralError("Error: "+obj.Error)})}}
function SendTransaction(){transObject=getTransactionObject(!0);null!=transObject&&(j=JSON.stringify(transObject),postRequest("send-transaction",j,function(a){obj=JSON.parse(a);"none"==obj.Error?(disableInput(),HideNewButtons(),SetGeneralSuccess("Transaction Sent, transaction ID: "+obj.Content),ShowNewTransaction()):(enableInput(),HideNewButtons(),$("#transaction-fee").attr("value","----"),$("#transaction-total").attr("value","----"),SetGeneralError("Error: "+obj.Error))}))}
$("#edit-transaction").on("click",function(){enableInput();HideNewButtons();$("#transaction-fee").attr("value","----");$("#transaction-total").attr("value","----");HideMessages()});
function LoadAddressesSendConvert(){resp=getRequest("addresses",function(a){obj=JSON.parse(a);null!=obj.FactoidAddresses.List&&obj.FactoidAddresses.List.forEach(function(a){$("#fee-addresses-reveal").append(factoidAddressRadio(a,"fee-address"))});"FCT"==PageTokenABR?(null!=obj.FactoidAddresses.List&&obj.FactoidAddresses.List.forEach(function(a){$("#addresses-reveal").append(factoidAddressRadio(a,"address"))}),null!=obj.ExternalAddresses.List&&obj.ExternalAddresses.List.forEach(function(a){a.Address.startsWith("FA")&&
$("#addresses-reveal").append(factoidAddressRadio(a,"address"))})):(null!=obj.EntryCreditAddresses.List&&obj.EntryCreditAddresses.List.forEach(function(a){$("#addresses-reveal").append(factoidECRadio(a,"address"))}),null!=obj.ExternalAddresses.List&&obj.ExternalAddresses.List.forEach(function(a){a.Address.startsWith("EC")&&$("#addresses-reveal").append(factoidECRadio(a,"address"))}))});$("#coin-control").hasClass("coin-control")&&$("#fee-address-input").css("display","none")}
function factoidAddressRadio(a,b){return'<pre>  <input type="radio" name="'+b+'" id="address" value="'+a.Address+'"> <span id="address-name" name="'+a.Name+'">'+a.Name+"</span></pre><br />"}$("#addresses-reveal").on("mouseover","#address-name",function(){$(this).css("font-size","90%");$(this).text($(this).parent().find("#address").val())});$("#addresses-reveal").on("mouseout","#address-name",function(){$(this).text($(this).attr("name"));$(this).css("font-size","100%")});
function factoidECRadio(a,b){return'<pre>  <input type="radio" name="address" id="address" value="'+a.Address+'"> <span id="address-name" name="'+a.Name+'">'+a.Name+"</span></pre> <br />"}$("#addresses-reveal").on("mouseover","#address-name",function(){$(this).css("font-size","90%");$(this).text($(this).parent().find("#address").val())});$("#addresses-reveal").on("mouseout","#address-name",function(){$(this).text($(this).attr("name"));$(this).css("font-size","100%")});done=!1;
$("#addresses-reveal-button").on("click",function(){newAddress=$("input[name='address']:checked").val();void 0!=newAddress&&($(".single-output-"+toChange+" #output-factoid-address").val(newAddress),$(".single-output-"+toChange+" #output-factoid-address-container").removeClass("input-group-error"))});toChange="-1";$("#all-outputs").on("click","#addressbook-button",function(){toChange=$(this).attr("value");$("input[type=radio]").attr("checked",!1)});
$("#all-inputs").on("click","#addressbook-button",function(){toChange=$(this).attr("value");$("input[type=radio]").attr("checked",!1)});$("#fee-address-input").on("click","#addressbook-button",function(){toChange=$(this).attr("value");$("input[type=radio]").attr("checked",!1)});
$("#fee-addresses-reveal-button").on("click",function(){newAddress=$("input[name='fee-address']:checked").val();void 0!=newAddress&&("-1"==toChange?($("#fee-factoid-address").val(newAddress),$("#fee-factoid-address").removeClass("input-group-error")):($(".single-input-"+toChange+" #input-factoid-address").val(newAddress),$(".single-input-"+toChange+" #input-factoid-address-container").removeClass("input-group-error")))});function HideNewButtons(){$("#second-stage-buttons").slideUp(100)}
function ShowNewButtons(){$("#export-transaction").slideDown(100);$("#broadcast-transaction").slideUp(100);$("#second-stage-buttons").slideDown(100)}function ShowNewTransaction(){$("#new-transaction").slideDown(100)}$("#new-transaction").on("click",function(){location.reload()});Input=!0;
function disableInput(){Input=!1;$(".input-group").each(function(){$(this).addClass("disabled-input");$(this).prop("disabled",!0)});$(".input-group-field").each(function(){$(this).addClass("disabled-input");$(this).prop("disabled",!0)});$("#needed-input-button").addClass("disabled-input");$("#needed-input-button").prop("disabled",!0);$("#addressbook-button").addClass("disabled-input");$("#addressbook-button").prop("disabled",!0);$("#make-entire-transaction").addClass("disabled-input");$("#make-entire-transaction").prop("disabled",
!0);$("#first-stage-buttons").slideUp(100);$("#import-file").addClass("disabled-input");$("#import-file").prop("disabled",!0)}
function enableInput(){Input=!0;$(".input-group").each(function(){$(this).removeClass("disabled-input");$(this).prop("disabled",!1)});$(".input-group-field").each(function(){$(this).removeClass("disabled-input");$(this).prop("disabled",!1)});$("#transaction-fee").prop("disabled",!0);$("#transaction-total").prop("disabled",!0);$("#needed-input-button").removeClass("disabled-input");$("#needed-input-button").prop("disabled",!1);$("#addressbook-button").removeClass("disabled-input");$("#addressbook-button").prop("disabled",
!1);$("#make-entire-transaction").removeClass("disabled-input");$("#make-entire-transaction").prop("disabled",!1);$("#first-stage-buttons").slideDown(100);$("#import-file").removeClass("disabled-input");$("#import-file").prop("disabled",!1);keepFeeDisabled()}function keepFeeDisabled(){$("#input-factoid-address").prop("disabled",!0);$("#input-factoid-address").addClass("disabled-input")}function HideMessages(){$("#error-zone").slideUp(100);$("#success-zone").slideUp(100)}
$("#import-file").on("click",function(){document.getElementById("uploaded-file").click()});$("#uploaded-file").on("change",function(){(input=document.getElementById("uploaded-file"))?input.files?input.files[0]?(file=input.files[0],fr=new FileReader,fr.onload=importTrans,fr.readAsText(file)):SetGeneralError("No file found"):SetGeneralError("This browser doesn't seem to support the `files` property of file inputs."):SetGeneralError("Error with upload file javascript.")});
function importTrans(){x=fr.result;postRequest("import-transaction",fr.result,function(a){obj=JSON.parse(a);if("none"==obj.Error){total=0;$("#all-inputs").html("");for(a=0;a<obj.Content.InputAddresses.length;a++)first=!1,0==a&&(first=!0),addNewInputAddress(obj.Content.InputAddresses[a],Number(obj.Content.InputAmounts[a]),!1,first),total+=obj.Content.InputAmounts[a];$("#all-outputs").html("");for(a=0;a<obj.Content.OutputAddresses.length;a++)first=!1,0==a&&(first=!0),addNewOutputAddress(obj.Content.OutputAddresses[a],
Number(obj.Content.OutputAmounts[a]),!1,first);obj.Content.Signature?$("#sign-transaction").attr("checked",!0):$("#sign-transaction").attr("checked",!1);disableInput();$("#transaction-total").val(Number(total));ShowNewButtons();$("#export-transaction").slideUp(1);$("#broadcast-transaction").slideDown(1)}else SetGeneralError(obj.Error)});console.log(fr.result)}
$("#broadcast-transaction").on("click",function(){$("#sign-transaction").prop("checked")?postRequest("broadcast-transaction",null,function(a){obj=JSON.parse(a);"none"==obj.Error?(SetGeneralSuccess("Transaction Sent, transaction ID: "+obj.Content),$("#broadcast-transaction").addClass("disabled-input"),$("#broadcast-transaction").prop("disabled",!0)):SetGeneralError(obj.Error)}):SetGeneralError("Transaction is not signed. Click the sign button if you contain the private keys to the inputs.")});
$("#save-changes").on("click",function(){theme=$("#darkTheme").is(":checked");exportKeys=$("#export-keys").is(":checked");coinControl=$("#coin-control").is(":checked");importExport=$("#import-export").is(":checked");fd=$("#factomd-location").val();$("#customFactomd").is(":checked")||(fd="localhost:8088");var a={Values:[],FactomdLocation:""};a.Values.push(theme);a.Values.push(exportKeys);a.Values.push(coinControl);a.Values.push(importExport);a.FactomdLocation=fd;j=JSON.stringify(a);postRequest("adjust-settings",
j,function(a){obj=JSON.parse(a);"none"==obj.Error?window.location.href.includes("success")?window.location.href=window.location.href:window.location.href+="?success=true":SetGeneralError("Error: "+obj.Error)})});$("#customFactomd").on("click",function(){$("#customFactomd").is(":checked")?$("#factomd-location-container").removeClass("hide"):$("#factomd-location-container").addClass("hide")});
$("#export-seed").on("click",function(){postRequest("get-seed","",function(a){obj=JSON.parse(a);"none"==obj.Error?saveTextAsFile(obj.Content,"WalletSeed.txt"):SetGeneralError("Error: "+obj.Error)})});$("#settings-import-file").on("click",function(a){document.getElementById("settings-uploaded-file").click()});
$("#settings-uploaded-file").on("change",function(){(input=document.getElementById("uploaded-file"))?input.files?input.files[0]?(file=input.files[0],fr=new FileReader,fr.onload=receivedText,fr.readAsText(file)):SetGeneralError("Please select a file before clicking 'Import From File'"):SetGeneralError("This browser doesn't seem to support the `files` property of file inputs."):SetGeneralError("Error: Couldn't find the fileinput element.")});
function receivedText(){is=fr.result;len=is.split(" ");12!=len.length?SetGeneralError("Seed must be 12 words"):(document.getElementById("data-expand").click(),$("#import-seed-reveal-text").text(fr.result),$("#import-seed-reveal-cancel").click())}
$("#import-seed-reveal-confirm").on("click",function(){seed=$("#import-seed-reveal-text").text();j=JSON.stringify({Seed:seed});postRequest("import-seed",j,function(a){obj=JSON.parse(a);"none"==obj.Error?SetGeneralSuccess("Seed has been changed to: "+obj.Content):SetGeneralError("Error: "+obj.Error)})});
function LoadRecAddresses(){resp=getRequest("addresses",function(a){obj=JSON.parse(a);null!=obj.FactoidAddresses.List&&obj.FactoidAddresses.List.forEach(function(a){$("#receiving-address").append(dropDownOption(a))});null!=obj.EntryCreditAddresses.List&&obj.EntryCreditAddresses.List.forEach(function(a){$("#receiving-address").append(dropDownOption(a))});null!=obj.ExternalAddresses.List&&obj.ExternalAddresses.List.forEach(function(a){$("#receiving-address").append(dropDownOption(a))});UpdateSelectedInfo()})}
function LoadFixedAddress(){add=$("#receiving-address-fixed small").text();updateWithGivenAddress(add)}function dropDownOption(a){return'<option value="'+a.Name+'">'+a.Name+" ("+a.Address+")</option>"}$("#rec-copy-to-clipboard").on("click",function(){var a=document.createElement("input");a.setAttribute("value",$("#selected-address-info").val());document.body.appendChild(a);a.select();document.execCommand("copy");document.body.removeChild(a)});$("#receiving-address").on("change",function(){UpdateSelectedInfo()});
function UpdateSelectedInfo(){add=$("#receiving-address option:selected").text();updateWithGivenAddress(add)}
function updateWithGivenAddress(a){splits=a.split("(");splits=splits[1].split(")");$("#selected-address-info").val(splits[0]);$("#selected-address-info").text(splits[0]);jsonOBJ='{"Address":"'+splits[0]+'"}';postRequest("get-address",jsonOBJ,function(a){obj=JSON.parse(a);"none"!=obj.Error?$("#balance").val("Error"):obj.Content.Address.startsWith("FA")?($("#balance").val(obj.Content.Balance.toFixed(8)),$("#balance-type").text("FCT")):($("#balance").val(obj.Content.Balance),$("#balance-type").text("EC"))});
$("#qrcode").text("");$("#qrcode").qrcode({width:256,height:256,text:splits[0]})}
(function(a){a.fn.qrcode=function(b){function c(a){this.mode=u;this.data=a}function g(a,f){this.typeNumber=a;this.errorCorrectLevel=f;this.modules=null;this.moduleCount=0;this.dataCache=null;this.dataList=[]}function q(a,f){if(void 0==a.length)throw Error(a.length+"/"+f);for(var d=0;d<a.length&&0==a[d];)d++;this.num=Array(a.length-d+f);for(var e=0;e<a.length-d;e++)this.num[e]=a[e+d]}function h(a,f){this.totalCount=a;this.dataCount=f}function v(){this.buffer=[];this.length=0}var u;c.prototype={getLength:function(){return this.data.length},
write:function(a){for(var d=0;d<this.data.length;d++)a.put(this.data.charCodeAt(d),8)}};g.prototype={addData:function(a){this.dataList.push(new c(a));this.dataCache=null},isDark:function(a,f){if(0>a||this.moduleCount<=a||0>f||this.moduleCount<=f)throw Error(a+","+f);return this.modules[a][f]},getModuleCount:function(){return this.moduleCount},make:function(){if(1>this.typeNumber){var a;for(a=1;40>a;a++){for(var f=h.getRSBlocks(a,this.errorCorrectLevel),t=new v,e=0,b=0;b<f.length;b++)e+=f[b].dataCount;
for(b=0;b<this.dataList.length;b++)f=this.dataList[b],t.put(f.mode,4),t.put(f.getLength(),m.getLengthInBits(f.mode,a)),f.write(t);if(t.getLengthInBits()<=8*e)break}this.typeNumber=a}this.makeImpl(!1,this.getBestMaskPattern())},makeImpl:function(a,f){this.moduleCount=4*this.typeNumber+17;this.modules=Array(this.moduleCount);for(var d=0;d<this.moduleCount;d++){this.modules[d]=Array(this.moduleCount);for(var e=0;e<this.moduleCount;e++)this.modules[d][e]=null}this.setupPositionProbePattern(0,0);this.setupPositionProbePattern(this.moduleCount-
7,0);this.setupPositionProbePattern(0,this.moduleCount-7);this.setupPositionAdjustPattern();this.setupTimingPattern();this.setupTypeInfo(a,f);7<=this.typeNumber&&this.setupTypeNumber(a);null==this.dataCache&&(this.dataCache=g.createData(this.typeNumber,this.errorCorrectLevel,this.dataList));this.mapData(this.dataCache,f)},setupPositionProbePattern:function(a,f){for(var d=-1;7>=d;d++)if(!(-1>=a+d||this.moduleCount<=a+d))for(var e=-1;7>=e;e++)-1>=f+e||this.moduleCount<=f+e||(this.modules[a+d][f+e]=
0<=d&&6>=d&&(0==e||6==e)||0<=e&&6>=e&&(0==d||6==d)||2<=d&&4>=d&&2<=e&&4>=e?!0:!1)},getBestMaskPattern:function(){for(var a=0,f=0,b=0;8>b;b++){this.makeImpl(!0,b);var e=m.getLostPoint(this);if(0==b||a>e)a=e,f=b}return f},createMovieClip:function(a,f,b){a=a.createEmptyMovieClip(f,b);this.make();for(f=0;f<this.modules.length;f++){b=1*f;for(var d=0;d<this.modules[f].length;d++){var t=1*d;this.modules[f][d]&&(a.beginFill(0,100),a.moveTo(t,b),a.lineTo(t+1,b),a.lineTo(t+1,b+1),a.lineTo(t,b+1),a.endFill())}}return a},
setupTimingPattern:function(){for(var a=8;a<this.moduleCount-8;a++)null==this.modules[a][6]&&(this.modules[a][6]=0==a%2);for(a=8;a<this.moduleCount-8;a++)null==this.modules[6][a]&&(this.modules[6][a]=0==a%2)},setupPositionAdjustPattern:function(){for(var a=m.getPatternPosition(this.typeNumber),f=0;f<a.length;f++)for(var b=0;b<a.length;b++){var e=a[f],w=a[b];if(null==this.modules[e][w])for(var c=-2;2>=c;c++)for(var l=-2;2>=l;l++)this.modules[e+c][w+l]=-2==c||2==c||-2==l||2==l||0==c&&0==l?!0:!1}},setupTypeNumber:function(a){for(var d=
m.getBCHTypeNumber(this.typeNumber),b=0;18>b;b++){var e=!a&&1==(d>>b&1);this.modules[Math.floor(b/3)][b%3+this.moduleCount-8-3]=e}for(b=0;18>b;b++)e=!a&&1==(d>>b&1),this.modules[b%3+this.moduleCount-8-3][Math.floor(b/3)]=e},setupTypeInfo:function(a,f){for(var d=m.getBCHTypeInfo(this.errorCorrectLevel<<3|f),e=0;15>e;e++){var b=!a&&1==(d>>e&1);6>e?this.modules[e][8]=b:8>e?this.modules[e+1][8]=b:this.modules[this.moduleCount-15+e][8]=b}for(e=0;15>e;e++)b=!a&&1==(d>>e&1),8>e?this.modules[8][this.moduleCount-
e-1]=b:9>e?this.modules[8][15-e-1+1]=b:this.modules[8][15-e-1]=b;this.modules[this.moduleCount-8][8]=!a},mapData:function(a,b){for(var d=-1,e=this.moduleCount-1,f=7,c=0,l=this.moduleCount-1;0<l;l-=2)for(6==l&&l--;;){for(var k=0;2>k;k++)if(null==this.modules[e][l-k]){var g=!1;c<a.length&&(g=1==(a[c]>>>f&1));m.getMask(b,e,l-k)&&(g=!g);this.modules[e][l-k]=g;f--; -1==f&&(c++,f=7)}e+=d;if(0>e||this.moduleCount<=e){e-=d;d=-d;break}}}};g.PAD0=236;g.PAD1=17;g.createData=function(a,b,c){b=h.getRSBlocks(a,
b);for(var d=new v,f=0;f<c.length;f++){var t=c[f];d.put(t.mode,4);d.put(t.getLength(),m.getLengthInBits(t.mode,a));t.write(d)}for(f=a=0;f<b.length;f++)a+=b[f].dataCount;if(d.getLengthInBits()>8*a)throw Error("code length overflow. ("+d.getLengthInBits()+">"+8*a+")");for(d.getLengthInBits()+4<=8*a&&d.put(0,4);0!=d.getLengthInBits()%8;)d.putBit(!1);for(;!(d.getLengthInBits()>=8*a);){d.put(g.PAD0,8);if(d.getLengthInBits()>=8*a)break;d.put(g.PAD1,8)}return g.createBytes(d,b)};g.createBytes=function(a,
b){for(var d=0,f=0,c=0,g=Array(b.length),l=Array(b.length),k=0;k<b.length;k++){var h=b[k].dataCount,n=b[k].totalCount-h,f=Math.max(f,h),c=Math.max(c,n);g[k]=Array(h);for(var p=0;p<g[k].length;p++)g[k][p]=255&a.buffer[p+d];d+=h;p=m.getErrorCorrectPolynomial(n);h=(new q(g[k],p.getLength()-1)).mod(p);l[k]=Array(p.getLength()-1);for(p=0;p<l[k].length;p++)n=p+h.getLength()-l[k].length,l[k][p]=0<=n?h.get(n):0}for(p=k=0;p<b.length;p++)k+=b[p].totalCount;d=Array(k);for(p=h=0;p<f;p++)for(k=0;k<b.length;k++)p<
g[k].length&&(d[h++]=g[k][p]);for(p=0;p<c;p++)for(k=0;k<b.length;k++)p<l[k].length&&(d[h++]=l[k][p]);return d};u=4;for(var m={PATTERN_POSITION_TABLE:[[],[6,18],[6,22],[6,26],[6,30],[6,34],[6,22,38],[6,24,42],[6,26,46],[6,28,50],[6,30,54],[6,32,58],[6,34,62],[6,26,46,66],[6,26,48,70],[6,26,50,74],[6,30,54,78],[6,30,56,82],[6,30,58,86],[6,34,62,90],[6,28,50,72,94],[6,26,50,74,98],[6,30,54,78,102],[6,28,54,80,106],[6,32,58,84,110],[6,30,58,86,114],[6,34,62,90,118],[6,26,50,74,98,122],[6,30,54,78,102,
126],[6,26,52,78,104,130],[6,30,56,82,108,134],[6,34,60,86,112,138],[6,30,58,86,114,142],[6,34,62,90,118,146],[6,30,54,78,102,126,150],[6,24,50,76,102,128,154],[6,28,54,80,106,132,158],[6,32,58,84,110,136,162],[6,26,54,82,110,138,166],[6,30,58,86,114,142,170]],G15:1335,G18:7973,G15_MASK:21522,getBCHTypeInfo:function(a){for(var d=a<<10;0<=m.getBCHDigit(d)-m.getBCHDigit(m.G15);)d^=m.G15<<m.getBCHDigit(d)-m.getBCHDigit(m.G15);return(a<<10|d)^m.G15_MASK},getBCHTypeNumber:function(a){for(var d=a<<12;0<=
m.getBCHDigit(d)-m.getBCHDigit(m.G18);)d^=m.G18<<m.getBCHDigit(d)-m.getBCHDigit(m.G18);return a<<12|d},getBCHDigit:function(a){for(var d=0;0!=a;)d++,a>>>=1;return d},getPatternPosition:function(a){return m.PATTERN_POSITION_TABLE[a-1]},getMask:function(a,b,c){switch(a){case 0:return 0==(b+c)%2;case 1:return 0==b%2;case 2:return 0==c%3;case 3:return 0==(b+c)%3;case 4:return 0==(Math.floor(b/2)+Math.floor(c/3))%2;case 5:return 0==b*c%2+b*c%3;case 6:return 0==(b*c%2+b*c%3)%2;case 7:return 0==(b*c%3+(b+
c)%2)%2;default:throw Error("bad maskPattern:"+a);}},getErrorCorrectPolynomial:function(a){for(var b=new q([1],0),d=0;d<a;d++)b=b.multiply(new q([1,n.gexp(d)],0));return b},getLengthInBits:function(a,b){if(1<=b&&10>b)switch(a){case 1:return 10;case 2:return 9;case u:return 8;case 8:return 8;default:throw Error("mode:"+a);}else if(27>b)switch(a){case 1:return 12;case 2:return 11;case u:return 16;case 8:return 10;default:throw Error("mode:"+a);}else if(41>b)switch(a){case 1:return 14;case 2:return 13;
case u:return 16;case 8:return 12;default:throw Error("mode:"+a);}else throw Error("type:"+b);},getLostPoint:function(a){for(var b=a.getModuleCount(),d=0,e=0;e<b;e++)for(var c=0;c<b;c++){for(var g=0,l=a.isDark(e,c),k=-1;1>=k;k++)if(!(0>e+k||b<=e+k))for(var h=-1;1>=h;h++)0>c+h||b<=c+h||0==k&&0==h||l==a.isDark(e+k,c+h)&&g++;5<g&&(d+=3+g-5)}for(e=0;e<b-1;e++)for(c=0;c<b-1;c++)if(g=0,a.isDark(e,c)&&g++,a.isDark(e+1,c)&&g++,a.isDark(e,c+1)&&g++,a.isDark(e+1,c+1)&&g++,0==g||4==g)d+=3;for(e=0;e<b;e++)for(c=
0;c<b-6;c++)a.isDark(e,c)&&!a.isDark(e,c+1)&&a.isDark(e,c+2)&&a.isDark(e,c+3)&&a.isDark(e,c+4)&&!a.isDark(e,c+5)&&a.isDark(e,c+6)&&(d+=40);for(c=0;c<b;c++)for(e=0;e<b-6;e++)a.isDark(e,c)&&!a.isDark(e+1,c)&&a.isDark(e+2,c)&&a.isDark(e+3,c)&&a.isDark(e+4,c)&&!a.isDark(e+5,c)&&a.isDark(e+6,c)&&(d+=40);for(c=g=0;c<b;c++)for(e=0;e<b;e++)a.isDark(e,c)&&g++;a=Math.abs(100*g/b/b-50)/5;return d+10*a}},n={glog:function(a){if(1>a)throw Error("glog("+a+")");return n.LOG_TABLE[a]},gexp:function(a){for(;0>a;)a+=
255;for(;256<=a;)a-=255;return n.EXP_TABLE[a]},EXP_TABLE:Array(256),LOG_TABLE:Array(256)},r=0;8>r;r++)n.EXP_TABLE[r]=1<<r;for(r=8;256>r;r++)n.EXP_TABLE[r]=n.EXP_TABLE[r-4]^n.EXP_TABLE[r-5]^n.EXP_TABLE[r-6]^n.EXP_TABLE[r-8];for(r=0;255>r;r++)n.LOG_TABLE[n.EXP_TABLE[r]]=r;q.prototype={get:function(a){return this.num[a]},getLength:function(){return this.num.length},multiply:function(a){for(var b=Array(this.getLength()+a.getLength()-1),c=0;c<this.getLength();c++)for(var d=0;d<a.getLength();d++)b[c+d]^=
n.gexp(n.glog(this.get(c))+n.glog(a.get(d)));return new q(b,0)},mod:function(a){if(0>this.getLength()-a.getLength())return this;for(var b=n.glog(this.get(0))-n.glog(a.get(0)),c=Array(this.getLength()),d=0;d<this.getLength();d++)c[d]=this.get(d);for(d=0;d<a.getLength();d++)c[d]^=n.gexp(n.glog(a.get(d))+b);return(new q(c,0)).mod(a)}};h.RS_BLOCK_TABLE=[[1,26,19],[1,26,16],[1,26,13],[1,26,9],[1,44,34],[1,44,28],[1,44,22],[1,44,16],[1,70,55],[1,70,44],[2,35,17],[2,35,13],[1,100,80],[2,50,32],[2,50,24],
[4,25,9],[1,134,108],[2,67,43],[2,33,15,2,34,16],[2,33,11,2,34,12],[2,86,68],[4,43,27],[4,43,19],[4,43,15],[2,98,78],[4,49,31],[2,32,14,4,33,15],[4,39,13,1,40,14],[2,121,97],[2,60,38,2,61,39],[4,40,18,2,41,19],[4,40,14,2,41,15],[2,146,116],[3,58,36,2,59,37],[4,36,16,4,37,17],[4,36,12,4,37,13],[2,86,68,2,87,69],[4,69,43,1,70,44],[6,43,19,2,44,20],[6,43,15,2,44,16],[4,101,81],[1,80,50,4,81,51],[4,50,22,4,51,23],[3,36,12,8,37,13],[2,116,92,2,117,93],[6,58,36,2,59,37],[4,46,20,6,47,21],[7,42,14,4,43,
15],[4,133,107],[8,59,37,1,60,38],[8,44,20,4,45,21],[12,33,11,4,34,12],[3,145,115,1,146,116],[4,64,40,5,65,41],[11,36,16,5,37,17],[11,36,12,5,37,13],[5,109,87,1,110,88],[5,65,41,5,66,42],[5,54,24,7,55,25],[11,36,12],[5,122,98,1,123,99],[7,73,45,3,74,46],[15,43,19,2,44,20],[3,45,15,13,46,16],[1,135,107,5,136,108],[10,74,46,1,75,47],[1,50,22,15,51,23],[2,42,14,17,43,15],[5,150,120,1,151,121],[9,69,43,4,70,44],[17,50,22,1,51,23],[2,42,14,19,43,15],[3,141,113,4,142,114],[3,70,44,11,71,45],[17,47,21,4,
48,22],[9,39,13,16,40,14],[3,135,107,5,136,108],[3,67,41,13,68,42],[15,54,24,5,55,25],[15,43,15,10,44,16],[4,144,116,4,145,117],[17,68,42],[17,50,22,6,51,23],[19,46,16,6,47,17],[2,139,111,7,140,112],[17,74,46],[7,54,24,16,55,25],[34,37,13],[4,151,121,5,152,122],[4,75,47,14,76,48],[11,54,24,14,55,25],[16,45,15,14,46,16],[6,147,117,4,148,118],[6,73,45,14,74,46],[11,54,24,16,55,25],[30,46,16,2,47,17],[8,132,106,4,133,107],[8,75,47,13,76,48],[7,54,24,22,55,25],[22,45,15,13,46,16],[10,142,114,2,143,115],
[19,74,46,4,75,47],[28,50,22,6,51,23],[33,46,16,4,47,17],[8,152,122,4,153,123],[22,73,45,3,74,46],[8,53,23,26,54,24],[12,45,15,28,46,16],[3,147,117,10,148,118],[3,73,45,23,74,46],[4,54,24,31,55,25],[11,45,15,31,46,16],[7,146,116,7,147,117],[21,73,45,7,74,46],[1,53,23,37,54,24],[19,45,15,26,46,16],[5,145,115,10,146,116],[19,75,47,10,76,48],[15,54,24,25,55,25],[23,45,15,25,46,16],[13,145,115,3,146,116],[2,74,46,29,75,47],[42,54,24,1,55,25],[23,45,15,28,46,16],[17,145,115],[10,74,46,23,75,47],[10,54,
24,35,55,25],[19,45,15,35,46,16],[17,145,115,1,146,116],[14,74,46,21,75,47],[29,54,24,19,55,25],[11,45,15,46,46,16],[13,145,115,6,146,116],[14,74,46,23,75,47],[44,54,24,7,55,25],[59,46,16,1,47,17],[12,151,121,7,152,122],[12,75,47,26,76,48],[39,54,24,14,55,25],[22,45,15,41,46,16],[6,151,121,14,152,122],[6,75,47,34,76,48],[46,54,24,10,55,25],[2,45,15,64,46,16],[17,152,122,4,153,123],[29,74,46,14,75,47],[49,54,24,10,55,25],[24,45,15,46,46,16],[4,152,122,18,153,123],[13,74,46,32,75,47],[48,54,24,14,55,
25],[42,45,15,32,46,16],[20,147,117,4,148,118],[40,75,47,7,76,48],[43,54,24,22,55,25],[10,45,15,67,46,16],[19,148,118,6,149,119],[18,75,47,31,76,48],[34,54,24,34,55,25],[20,45,15,61,46,16]];h.getRSBlocks=function(a,b){var c=h.getRsBlockTable(a,b);if(void 0==c)throw Error("bad rs block @ typeNumber:"+a+"/errorCorrectLevel:"+b);for(var d=c.length/3,f=[],g=0;g<d;g++)for(var l=c[3*g+0],k=c[3*g+1],m=c[3*g+2],n=0;n<l;n++)f.push(new h(k,m));return f};h.getRsBlockTable=function(a,b){switch(b){case 1:return h.RS_BLOCK_TABLE[4*
(a-1)+0];case 0:return h.RS_BLOCK_TABLE[4*(a-1)+1];case 3:return h.RS_BLOCK_TABLE[4*(a-1)+2];case 2:return h.RS_BLOCK_TABLE[4*(a-1)+3]}};v.prototype={get:function(a){return 1==(this.buffer[Math.floor(a/8)]>>>7-a%8&1)},put:function(a,b){for(var c=0;c<b;c++)this.putBit(1==(a>>>b-c-1&1))},getLengthInBits:function(){return this.length},putBit:function(a){var b=Math.floor(this.length/8);this.buffer.length<=b&&this.buffer.push(0);a&&(this.buffer[b]|=128>>>this.length%8);this.length++}};"string"===typeof b&&
(b={text:b});b=a.extend({},{render:"canvas",width:256,height:256,typeNumber:-1,correctLevel:2,background:"#ffffff",foreground:"#000000"},b);return this.each(function(){var c;if("canvas"==b.render){c=new g(b.typeNumber,b.correctLevel);c.addData(b.text);c.make();var f=document.createElement("canvas");f.width=b.width;f.height=b.height;for(var h=f.getContext("2d"),e=b.width/c.getModuleCount(),n=b.height/c.getModuleCount(),m=0;m<c.getModuleCount();m++)for(var l=0;l<c.getModuleCount();l++)h.fillStyle=c.isDark(m,
l)?b.foreground:b.background,h.fillRect(Math.round(l*e),Math.round(m*n),Math.ceil((l+1)*e)-Math.floor(l*e),Math.ceil((m+1)*e)-Math.floor(m*e))}else for(c=new g(b.typeNumber,b.correctLevel),c.addData(b.text),c.make(),f=a("<table></table>").css("width",b.width+"px").css("height",b.height+"px").css("border","0px").css("border-collapse","collapse").css("background-color",b.background),h=b.width/c.getModuleCount(),e=b.height/c.getModuleCount(),n=0;n<c.getModuleCount();n++)for(m=a("<tr></tr>").css("height",
e+"px").appendTo(f),l=0;l<c.getModuleCount();l++)a("<td></td>").css("width",h+"px").css("background-color",c.isDark(n,l)?b.foreground:b.background).appendTo(m);jQuery(f).appendTo(this)})}})(jQuery);
$("#generate-source").on("change",function(){selected=$("#generate-source option:selected").val();"new-external-address"==selected?$("#sec-pub").text("Public"):$("#sec-pub").text("Private");"import-address"==selected||"new-external-address"==selected||"import-koinify"==selected?($("#private-key-input").prop("disabled",!1),$("#private-key-input").removeClass("disabled-input"),$("#nickname-input").addClass("input-group-error"),$("#private-key-input-container").addClass("input-group-error")):($("#private-key-input").prop("disabled",
!0),$("#private-key-input").addClass("disabled-input"),$("#nickname-input").addClass("input-group-error"),$("#private-key-input-container").removeClass("input-group-error"))});$("#private-key-input-container").on("click",function(){$(this).removeClass("input-group-error")});$("#nickname-input").on("click",function(){$(this).removeClass("input-group-error")});
$("#generate-source").on("change",function(){selected=$("#generate-source option:selected").val();$("#private-key-input").val("");"import-address"==selected?$("#private-key-input").attr("placeholder","Type address private key"):"random-ec"==selected?$("#private-key-input").attr("placeholder","A new entry credit address will be created"):"random-factoid"==selected?$("#private-key-input").attr("placeholder","A new factoid address will be created"):"new-external-address"==selected?$("#private-key-input").attr("placeholder",
"Type a public address to add to your contacts"):"import-koinify"==selected&&$("#private-key-input").attr("placeholder","Type in your Koinify phrase")});
$("#add-to-addressbook").on("click",function(){$("#error-zone").slideUp(100);Name=$("#nickname-input").val();""==Name?(SetError("Need a NickName for the new address"),$("#nickname-input").addClass("input-group-error")):(selected=$("#generate-source option:selected").val(),"import-address"==selected?(sec=$("#private-key-input").val(),sec.startsWith("Fs")||sec.startsWith("Es")?postRequest("is-valid-address",sec,function(a){"false"==a?(SetError("Not a valid private key."),$("#private-key-input-container").addClass("input-group-error")):
(j=JSON.stringify({Name:Name,Secret:sec}),postRequest("new-address",j,function(a){obj=JSON.parse(a);"none"==obj.Error?SetSuccess(obj):SetError(obj.Error)}))}):(SetError("Not a valid private key. Should start with 'Fs' for a factoid address or 'Es' for an entry credit address"),$("#private-key-input-container").addClass("input-group-error"))):"random-ec"==selected?postRequest("generate-new-address-ec",Name,function(a){obj=JSON.parse(a);"none"==obj.Error?SetSuccess(obj):SetError(obj.Error)}):"random-factoid"==
selected?postRequest("generate-new-address-factoid",Name,function(a){obj=JSON.parse(a);"none"==obj.Error?SetSuccess(obj):SetError(obj.Error)}):"new-external-address"==selected?(pub=$("#private-key-input").val(),pub.startsWith("FA")||pub.startsWith("EC")?postRequest("is-valid-address",pub,function(a){"false"==a?(SetError("Not a valid public key."),$("#private-key-input-container").addClass("input-group-error")):(j=JSON.stringify({Name:Name,Public:pub}),postRequest("new-external-address",j,function(a){obj=
JSON.parse(a);"none"==obj.Error?SetSuccess(obj):SetError(obj.Error)}))}):(SetError("Not a valid public key. Should start with 'FA' for a factoid address or 'EC' for an entry credit address. This option adds an address to your external addresses for easier use."),$("#private-key-input-container").addClass("input-group-error"))):"import-koinify"==selected?(koinify=$("#private-key-input").val(),j=JSON.stringify({Name:Name,Koinify:koinify}),postRequest("import-koinify",j,function(a){obj=JSON.parse(a);
"none"==obj.Error?SetSuccess(obj):SetError(obj.Error)})):SetError("An error has occurred. No address type selected, please try selecting from the dropdown menu again, or reload this page."))});function SetError(a){$("#success-zone").slideUp(100);$("#error-zone").text(a);$("#error-zone").slideDown(100)}
function SetSuccess(a){$("#error-zone").slideUp(100);$("#success-link").attr("href","/receive-factoids?address="+a.Content.Address+"&name="+a.Content.Name);$("#success-zone > #name").text(a.Content.Name);$("#success-zone > pre").text(a.Content.Address);$("#success-zone").slideDown(100)}var Name="",Address="";
function GetDefaultData(){Name=$("#address-name").val();Address=$("#address-field").val();jsonOBJ='{"Address":"'+Address+'"}';postRequest("get-address",jsonOBJ,function(a){obj=JSON.parse(a);"none"!=obj.Error?$("#balance-container").text("Can not find the addresses in address book"):obj.Content.Address.startsWith("FA")?$("#balance").text(obj.Content.Balance.toFixed(8)):$("#balance").text(obj.Content.Balance)})}
$("#display-private-key").click(function(){jsonOBJ='{"Address":"'+Address+'"}';postRequest("display-private-key",jsonOBJ,function(a){obj=JSON.parse(a);"none"!=obj.Error?($("#private-key-field").val(obj.Error),SetGeneralError("Error: "+obj.Error)):$("#private-key-field").val(obj.Content)})});
$("#save-name-change").click(function(){NewName=$("#address-name").val();jsonOBJ='{"Address":"'+Address+'", "Name":"'+NewName+'"}';NewName!=Name?postRequest("address-name-change",jsonOBJ,function(a){obj=JSON.parse(a);"none"!=obj.Error?SetGeneralError("Error: "+obj.Error):SetGeneralSuccess(obj.Content+": The name has been changed")}):SetGeneralError("Newname is the same as the original")});
$("#delete-address").on("click",function(){name=$("#address-name").val();jsonOBJ='{"Address":"'+Address+'", "Name":"'+name+'"}';postRequest("delete-address",jsonOBJ,function(a){obj=JSON.parse(a);"none"!=obj.Error?SetGeneralError("Error: "+obj.Error):SetGeneralSuccess(obj.Content+": The name has been changed")})});
$("#copy-to-clipboard").on("click",function(){var a=document.createElement("input");a.setAttribute("value",$("#private-key-field").val());document.body.appendChild(a);a.select();document.execCommand("copy");document.body.removeChild(a)});
